"""table comment add column disabled

Revision ID: 5302d6731456
Revises: f7dbbd748d3c
Create Date: 2017-08-04 18:19:23.776794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5302d6731456'
down_revision = 'f7dbbd748d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
